[features]
seeds = false
skip-lint = false

[programs.devnet]
bridge_solana = "56aoBWVLjwpHD8HHS4i7hBicbznFGMdYjWPVBprVWi6k"

[programs.mainnet]
bridge_solana = "56aoBWVLjwpHD8HHS4i7hBicbznFGMdYjWPVBprVWi6k"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "https://solana-api.syndica.io/access-token/uzvWwcrw5VkSnCLYSC7es8bC6uWcVU92YzMppv9w6Zny6arqbWpEEizr6IfTPE7e/rpc"
cluster = "devnet"
wallet = "/Users/chou/Developer/bridge-solana/tests/test_wallets/mainnet-admin.json"

[scripts]
mint = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/mint.ts"
burn = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/burn.ts"
init = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/init.ts"
updateTokenConfig = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/admin/updateTokenConfig.ts"
emergencyPause = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/admin/emergencyPause.ts"
